# global:
#   identity:
#     auth:
#       # Disable the Identity authentication for local development
#       # it will fall back to basic-auth: demo/demo as default user
#       enabled: false

# # Disable identity as part of the Camunda core
# identity:
#   enabled: false

# # Disable keycloak
# identityKeycloak:
#   enabled: false

# optimize:
#   enabled: false

# # Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# # to get it running locally
# zeebe:
#   clusterSize: 1
#   partitionCount: 1
#   replicationFactor: 1
#   pvcSize: 10Gi

# zeebeGateway:
#   replicas: 1

# connectors:
#   enabled: true
#   inbound:
#     mode: disabled

# elasticsearch:
#   master:
#     replicaCount: 1
#     # Request smaller persistent volumes.
#     persistence:
#       size: 15Gi


global:
  identity:
    auth:
      enabled: false

identity:
  enabled: false

identityKeycloak:
  enabled: false

optimize:
  enabled: false

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1024Mi
      cpu: 800m

zeebeGateway:
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

connectors:
  enabled: false

elasticsearch:
  enabled: true
  master:
    replicaCount: 1
    persistence:
      size: 15Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1024Mi
        cpu: 800m

